global using DomainServices.Interfaces.Services;
global using Microsoft.AspNetCore.Identity;
global using DomainServices.Exceptions;
global using System.Text.RegularExpressions;
global using System.Security.Cryptography;
global using System.Text;
global using System.Security.Cryptography.X509Certificates;
global using Domain;
global using System.Security.Claims;
